export const projectsData = [
  {
    id: 1,
    title: "Charlie's Story (without Framework)",
    date: "August 31, 2022 → October 19, 2024",
    description: "Personal Story Website",
    skills: "HTML, Java, CSS",
    members: 1,
    position: "Full Stack",
    github: "https://github.com/Charlie0921/CharlieStory.git",
    website: "https://chocolatefactory02.netlify.app",
    details: {
      background: "Charlie Story Background",
      whatItDoes: "Charlie Story what it does",
      challenges: "Charlie Story challenges",
      resolution: "Charlie Story resolution",
      accomplishments: "Charlie Story Accomplishments",
      lessonsLearned: "Charlie Story Lessons",
    },
    image: "../../img/ProjectImg/CharlieStory.webp",
  },
  {
    id: 2,
    title: "Tanyak Laundry",
    date: "August 4, 2024 → January 22, 2025",
    description:
      "A laundry management web-app used by military residents that displays machine usage with notifications",
    skills: "React.js, CSS, HTML, TypeScript",
    members: 2,
    position: "UI/UX Design, Front-end",
    github: "https://github.com/albert-yim/tanyak-laundry.git",
    website: "tanyak20.netlify.app",
    details: {
      background: "Tanyak Laundry background",
      whatItDoes: "Tanyak Laundry what it does",
      challenges: "Tanyak Laundry challenges",
      resolution: "Tanyak Laundry resolution",
      accomplishments: "Tanyak Laundry accomplishments",
      lessonsLearned: "Tanyak Laundry Lessons",
    },
    image: "../../img/ProjectImg/TanyakLaundry.webp",
  },
  {
    id: 3,
    title: "Faulty Sewage Pipe AI Detector",
    date: "June 17, 2024 → June 21, 2024",
    description:
      "Competition to classify sewage pipe faults and earn top Public Test Score",
    skills: "Yolo, Jupyter, Python",
    members: 2,
    position: "Developing and maintaining machine learning models",
    github: "",
    website:
      "https://www.wevity.com/index_university.php?c=find&s=_university&gbn=viewok&gp=4&ix=85983",
    details: {
      background: "Faulty Sewage Background",
      whatItDoes: "Faulty Sewage What it does",
      challenges: "Faulty sewage challenges",
      resolution: "Faulty Sewage resolution",
      accomplishments: "Faulty Sewage accomplishments",
      lessonsLearned: "Faulty Sewage lessons",
    },
    image: "../../img/ProjectImg/SewageClassifier.webp",
  },
  {
    id: 4,
    title: "Responsive TodoList (without framework)",
    date: "March 1, 2024 → March 24, 2024",
    description: "A responsive to-do list without using any framework.",
    skills: "HTML, CSS, JavaScript",
    members: 2,
    position: "UI/UX Design, Front-end",
    github: "https://github.com/Charlie0921/responsive-todo.git",
    website: "https://rokaf-to-do-list.netlify.app/",
    details: {
      background: "",
      whatItDoes: "",
      challenges: "",
      resolution: "",
      accomplishments: "",
      lessonsLearned: "",
    },
    image: "../../img/ProjectImg/ToDoList.webp",
  },
  {
    id: 5,
    title: "BeyondClass",
    date: "June 23, 2022 → April 23, 2023",
    description:
      "Website to provide students with competition, scholarship, and networking info.",
    skills: "React.js, JavaScript, CSS, HTML",
    members: 5,
    position: "Tech Lead: Front-end Developer, UI/UX Designer",
    github: "",
    website: "https://beyondclassmvp.netlify.app",
    details: {
      background: "",
      whatItDoes: "",
      challenges: "",
      resolution: "",
      accomplishments: "",
      lessonsLearned: "",
    },
    image: "../../img/ProjectImg/beyondclass.webp",
  },
  {
    id: 6,
    title: "PSUStudyFinder",
    date: "April 10, 2022 → April 11, 2022",
    description: "",
    skills: "Java, Three.js",
    members: 3,
    position: "Front-end Developer, UI/UX Designer",
    github: "https://devpost.com/software/psustudyfinder",
    website: "https://devpost.com/software/psustudyfinder",
    details: {
      background: "",
      whatItDoes: "",
      challenges: "",
      resolution: "",
      accomplishments: "",
      lessonsLearned: "",
    },
    image: "",
  },
  {
    id: 7,
    title: "Mapping Space Trash",
    date: "October 1, 2021 → October 3, 2021",
    description:
      "3D renders of Earth, which also displays and locates every known debris object orbiting Earth in real time",
    skills: "JavaScript, Three.js, React.js, CSS",
    members: 3,
    position: "Front-end Developer",
    github: "https://github.com/TheStargazers21",
    website:
      "https://2021.spaceappschallenge.org/challenges/statements/mapping-space-trash-in-real-time/teams/the-stargazers/project",
    details: {
      background: "",
      whatItDoes: "",
      challenges: "",
      resolution: "",
      accomplishments: "",
      lessonsLearned: "",
    },
    image: "",
  },
];
