"use client";
import { useEffect, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { TRACKS } from "@/lib/data";

export default function PlaylistWindow() {
  const [idx, setIdx] = useState(0); const [playing, setPlaying] = useState(false); const [progress, setProgress] = useState(24); const reduce = useReducedMotion();
  useEffect(() => { if (!playing) return; const timer = setInterval(() => setProgress(p => p >= 100 ? 0 : p + 1), 800); return () => clearInterval(timer); }, [playing]);
  return <div className="mx-auto max-w-xl"><p className="mb-5 text-sm text-ink-soft">A small soundtrack for the room. The player is decorative — bring your own headphones.</p><div className="rounded-2xl border border-line bg-white p-5"><div className="flex flex-col items-center gap-5 sm:flex-row"><motion.div animate={playing && !reduce ? { rotate: 360 } : {}} transition={{ repeat: Infinity, ease: "linear", duration: 7 }} className="grid h-32 w-32 flex-none place-items-center rounded-full bg-[conic-gradient(#557d92,#b8a9ce,#d08072,#557d92)] shadow-soft"><div className="grid h-11 w-11 place-items-center rounded-full bg-paper-bright font-accent text-base text-ink-soft">BGM</div></motion.div><div className="w-full"><p className="eyebrow">Now selected</p><h3 className="font-display text-2xl font-semibold text-ink">{TRACKS[idx].title}</h3><p className="text-sm text-ink-soft">{TRACKS[idx].artist}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-mist"><div className="h-full bg-coral transition-all" style={{ width: `${progress}%` }} /></div><button onClick={() => setPlaying(p => !p)} aria-pressed={playing} className="mt-4 rounded-full border border-coral-deep bg-coral px-5 py-2 font-accent text-lg uppercase tracking-[0.08em] text-white">{playing ? "Pause" : "Play demo"}</button></div></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{TRACKS.map((track, i) => <button key={track.title} onClick={() => { setIdx(i); setProgress(0); }} className={`flex items-center justify-between rounded-lg border p-3 text-left ${idx === i ? "border-coral bg-white" : "border-line bg-mist/60"}`}><span><strong className="block text-sm text-ink">{track.title}</strong><small className="text-ink-soft">{track.artist}</small></span><span className="font-accent text-base text-coral-deep">0{i + 1}</span></button>)}</div></div>;
}
